version: '2'

services:
  dockertest:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.release
      args:
      - CONTAINER_PORT=${DOCKERTEST_PORT}
      - SERVER_URLS=http://*:${DOCKERTEST_PORT}
    ports:
    - "${HOST_PORT}:${DOCKERTEST_PORT}"
